Django_web/urls.py
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings
from app01.views import admin, depart, user, pretty, account, task, order, chart, upload, city

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    # 管理员管理
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    # 部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    # 以后在访问edit页面时，必须以http://127.0.0.1:8000/depart/1/edit/这样的形式，即中间夹个数字
    path('depart/<int:nid>/edit/', depart.depart_edit),
    path('depart/multi/', depart.depart_multi),

    # 用户管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/model/form/add/', user.user_model_form_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),

    # 靓号管理
    path('pretty/list/', pretty.pretty_list),
    path('pretty/add/', pretty.pretty_add),
    path('pretty/<int:nid>/edit/', pretty.pretty_edit),
    path('pretty/<int:nid>/delete/', pretty.pretty_delete),

    # 用户登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    # 任务管理
    path('task/list/', task.task_list),
    path('task/ajax/', task.task_ajax),
    path('task/add/', task.task_add),

    # 订单管理
    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/delete/', order.order_delete),
    path('order/detail/', order.order_detail),
    path('order/edit/', order.order_edit),

    # 数据统计
    path('chart/list/', chart.chart_list),
    path('chart/bar/', chart.chart_bar),
    path('chart/pie/', chart.chart_pie),

    # 上传文件
    path('upload/list/', upload.upload_list),
    path('upload/form/', upload.upload_form),
    path('upload/modal/form/', upload.upload_form_modal),

    # 城市列表
    path('city/list/', city.city_list),
    path('city/add/', city.city_add),
]

app01/models.py
from django.db import models


# Create your models here.

class Admin(models.Model):
    # 管理员表
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    def __str__(self):
        return self.username


class Department(models.Model):
    # 部门表
    title = models.CharField(verbose_name='标题', max_length=32)

    # 定制了print(Department)时显示的内容是部门的名称
    def __str__(self):
        return self.title


class UserInfo(models.Model):
    # 员工表
    name = models.CharField(verbose_name='姓名', max_length=16)
    password = models.CharField(verbose_name='密码', max_length=64)

    # Django中有的约束
    sex_choices = (
        (1, "男"),
        (2, "女")
    )
    sex = models.SmallIntegerField(verbose_name='性别', choices=sex_choices)

    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    create_time = models.DateField(verbose_name='入职时间')

    '''
    使depart与部门表约束
    to决定了与哪一张表有关联，to_field决定与这张表中的哪一列有关联
    Django有个机制，凡是这种与其他表有约束的列，均会在定义的列名后加上"_id"
    '''
    # 如果需要级联删除，那么写上on_delete=models.CASCADE
    depart = models.ForeignKey(to='Department', to_field='id', on_delete=models.CASCADE, verbose_name="部门")
    # 如果置空，那么首先这一列需要满足为可空
    # depart = models.ForeignKey(to='Department', to_field='id',null=True, blank=True, on_delete=models.SET_NULL)


class PrettyNum(models.Model):
    # 靓号表
    mobile = models.CharField(verbose_name="手机号", max_length=11)
    price = models.IntegerField(verbose_name="价格", default=0)

    level_choices = (
        (1, "1级"),
        (2, "2级"),
        (3, "3级"),
        (4, "4级"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)

    status_choices = (
        (1, "已占用"),
        (2, "未占用")
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)


class Task(models.Model):
    # 任务
    level_choices = {
        (1, "紧急"),
        (2, "常规"),
        (3, "临时"),
    }
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=2)
    title = models.CharField(verbose_name="标题", max_length=64)
    detail = models.TextField(verbose_name="详细信息", max_length=100)
    user = models.ForeignKey(verbose_name="负责人", to='Admin', on_delete=models.CASCADE)


class Order(models.Model):
    # 工单
    oid = models.CharField(verbose_name="订单号", max_length=64)
    title = models.CharField(verbose_name="名称", max_length=32)
    price = models.IntegerField(verbose_name="价格")

    status_choices = {
        (1, "待支付"),
        (2, "已支付")
    }
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)

    admin = models.ForeignKey(verbose_name="管理员", to='Admin', on_delete=models.CASCADE)


class Boss(models.Model):
    # 老板
    name = models.CharField(verbose_name="姓名", max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    img = models.CharField(verbose_name="头像", max_length=128)


class City(models.Model):
    # 城市
    name = models.CharField(verbose_name="名称", max_length=32)
    count = models.IntegerField(verbose_name="人口")
    # 本质上FileField也是CharField，多了一个django内部帮你做保存的功能
    # upload_to会帮你将文件保存到media文件夹下某一文件夹
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='city/')

app01/views/account.py
from io import BytesIO

from django import forms
from django.shortcuts import render, HttpResponse, redirect

from app01 import models
from app01.utils.bootstrap import BootStrapForm
from app01.utils.encrypt import md5
from app01.utils.code import check_code


class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(render_value=True),
        required=True
    )
    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get('password')

        return md5(pwd)


def login(request):
    # 用户登录
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 验证成功，得到用户名和密码和验证码
        # form.cleaned_data

        # 验证码的校验
        # 用pop的原因是因为去数据库校验的时候只拿用户名和密码，与验证码无关
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', '')

        if code.upper() != user_input_code.upper():
            form.add_error('code', '验证码错误')
            return render(request, 'login.html', {'form': form})

        # 验证码对了，拿着用户名和密码去数据库校验
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            # 主动在form中添加错误信息，并传到前端
            form.add_error('password', '用户名或密码错误')
            return render(request, 'login.html', {'form': form})

        # 用户名和密码输入正确
        # 网站要生成一个随机字符串，写入到用户浏览器的cookie中，并写入到session中
        request.session['info'] = {'id': admin_object.id, 'name': admin_object.username}
        # session可以保存7天
        request.session.set_expiry(60 * 60 * 24 * 7)

        return redirect('/admin/list/')

    return render(request, 'login.html', {'form': form})


def logout(request):
    # 注销
    request.session.clear()

    return redirect('/login')


def image_code(request):
    # 生成验证码

    # 调用pillow函数，生成图片
    img, code_string = check_code()
    # 得到生成的验证码文本
    print(code_string)

    # 写入到session中，以便于后续获取并进行校验
    request.session['image_code'] = code_string
    # 设置一个60s超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')

    return HttpResponse(stream.getvalue())

app01/views/admin.py
from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect

from app01 import models
from app01.utils.encrypt import md5
from app01.utils.pagination import Pagination
from app01.utils.bootstrap import BootStrapModelForm


def admin_list(request):
    # 管理员列表

    # 搜索功能
    data_dict = {}
    # GET.get方法的第二个参数表示如果没有从GET方法中取到第一个参数，取的default值
    search_data = request.GET.get('q', "")
    if search_data:
        data_dict["username__contains"] = search_data

    # 根据搜索条件去获取数据库中的记录
    queryset = models.Admin.objects.filter(**data_dict)

    # 分页功能
    page_object = Pagination(request, queryset)

    context = {
        'queryset': page_object.page_queryset,
        'page_string': page_object.html(),
        'search_data': search_data
    }

    return render(request, 'admin_list.html', context)


class AdminModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput
    )

    class Meta:
        model = models.Admin
        fields = ['username', 'password', 'confirm_password']
        widgets = {
            'password': forms.PasswordInput
        }

    def clean_password(self):
        password = self.cleaned_data.get('password')  # 得到第一次输入的密码

        return md5(password)

    # 钩子函数
    def clean_confirm_password(self):
        # print(self.cleaned_data)
        password = self.cleaned_data.get('password')  # 得到第一次输入的密码
        confirm = md5(self.cleaned_data.get('confirm_password'))  # 确认的密码
        if confirm != password:
            raise ValidationError("密码不一致！")

        # 返回的值会写入cleaned_data中，所以，对于clean_confirm_password函数返回的应该是confirm_password
        return confirm


def admin_add(request):
    # 添加管理员
    context = {
        'title': "新建管理员"
    }

    if request.method == 'GET':
        form = AdminModelForm()
        context['form'] = form

        return render(request, 'change.html', context)

    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        # 通过form.cleaned_data可以得到用户在本页面提交的所有信息
        form.save()
        return redirect('/admin/list/')

    context['form'] = form
    return render(request, 'change.html', context)


class AdminEditModelForm(BootStrapModelForm):
    class Meta:
        model = models.Admin
        fields = ['username']


def admin_edit(request, nid):
    # 编辑管理员

    # 如果对象存在，则获取，如果不存在，只能拿到NULL
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'error.html', {'msg': "对象不存在！"})

    title = "编辑管理员"

    if request.method == "GET":
        form = AdminEditModelForm(instance=row_object)
        return render(request, 'change.html', {"form": form, "title": title})

    form = AdminEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')

    return render(request, 'change.html', {"form": form, "title": title})


def admin_delete(request, nid):
    # 删除管理员
    models.Admin.objects.filter(id=nid).delete()

    return redirect('/admin/list/')


class AdminResetModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput
    )

    class Meta:
        model = models.Admin
        fields = ['password', 'confirm_password']
        widgets = {
            'password': forms.PasswordInput
        }

    def clean_password(self):
        password = self.cleaned_data.get('password')  # 得到第一次输入的密码
        md5_pwd = md5(password)

        # 去数据库找一下原密码经md5加密之后的值和现密码经md5加密后的值一不一样
        exist = models.Admin.objects.filter(id=self.instance.pk, password=md5_pwd).exists()
        if exist:
            # print("存在！")
            raise ValidationError("不能与之前的密码相同")

        return md5_pwd

    # 钩子函数
    def clean_confirm_password(self):
        # print(self.cleaned_data)
        password = self.cleaned_data.get('password')  # 得到第一次输入的密码
        confirm = md5(self.cleaned_data.get('confirm_password'))  # 确认的密码
        if confirm != password:
            raise ValidationError("密码不一致！")

        # 返回的值会写入cleaned_data中，所以，对于clean_confirm_password函数返回的应该是confirm_password
        return confirm


def admin_reset(request, nid):
    # 重置密码
    # 如果对象存在，则获取，如果不存在，只能拿到NULL
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'error.html', {'msg': "对象不存在！"})

    title = "重置密码 - {}".format(row_object.username)

    if request.method == 'GET':
        form = AdminResetModelForm()
        return render(request, 'change.html', {'title': title, 'form': form})

    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list')

    return render(request, 'change.html', {'title': title, 'form': form})

app01/views/chart.py
import json
import random
from datetime import datetime

from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from app01 import models
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination


def chart_list(request):
    # 数据统计页面
    return render(request, 'chart_list.html')


def chart_bar(request):
    # 构造柱状图数据
    # 这里是写死了 但也可以从数据库中去获取
    legend = ["销量", "成本"]
    data_list = [
        {
            'name': '销量',
            'type': 'bar',
            'data': [5, 20, 36, 10, 10, 20]
        },
        {
            'name': '成本',
            'type': 'bar',
            'data': [10, 15, 3, 100, 11, 2]
        }
    ]
    x_list = ['衬衫', '羊毛衫', '雪纺衫', '裤子', '高跟鞋', '袜子']

    result = {
        'status': True,
        'data': {
            'legend': legend,
            'data_list': data_list,
            'x_list': x_list
        }
    }

    return JsonResponse(result)


def chart_pie(request):
    # 构造饼图数据
    db_data_list = [
        {'value': 2048, 'name': 'IT部门'},
        {'value': 1735, 'name': '运营'},
        {'value': 580, 'name': '新媒体'},
    ]

    result = {
        'status': True,
        'data': db_data_list
    }
    return JsonResponse(result)

app01/views/city.py
import json
import random
import os
from datetime import datetime

from django import forms
from django.shortcuts import render, HttpResponse, redirect
from django.conf import settings

from app01 import models
from app01.utils.bootstrap import BootStrapModelForm, BootStrapForm
from app01.utils.pagination import Pagination


def city_list(request):
    queryset = models.City.objects.all()

    return render(request, 'city_list.html', {'queryset': queryset})


class UpModalForm(BootStrapModelForm):
    bootstrap_exclude_field = ['img']

    class Meta:
        model = models.City
        fields = '__all__'


def city_add(request):
    title = "新建城市"
    if request.method == 'GET':
        form = UpModalForm()
        return render(request, 'upload_form.html', {'form': form, 'title': title})

    form = UpModalForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()

        return redirect('/city/list/')

    return render(request, 'upload_form.html', {'form': form, 'title': title})

app01/views/depart.py
from django.shortcuts import render, redirect, HttpResponse
from django.core.files.uploadedfile import InMemoryUploadedFile
from openpyxl import load_workbook

from app01 import models

from app01.utils.pagination import Pagination


def depart_list(request):
    # 部门列表

    # 去数据库中找到所有的部门信息
    queryset = models.Department.objects.all()

    query_object = Pagination(request, queryset)
    context = {
        'queryset': query_object.page_queryset,
        'page_string': query_object.html()
    }

    return render(request, "depart_list.html", context)


def depart_add(request):
    # 添加部门
    if request.method == "GET":
        return render(request, "depart_add.html")

    # 获取用户提交的数据
    title = request.POST.get("title")

    # 保存到数据库
    models.Department.objects.create(title=title)

    # 回到显示页面
    return redirect("/depart/list")


def depart_delete(request):
    # 删除部门

    # 获取id
    nid = request.GET.get('nid')
    # 删除
    models.Department.objects.filter(id=nid).delete()

    # 回到显示页面
    return redirect("/depart/list")
    # return HttpResponse("删除成功")


def depart_edit(request, nid):
    # 编辑部门

    if request.method == "GET":
        # 根据nid获取该行的数据
        row_object = models.Department.objects.filter(id=nid).first()
        # print(row_object.id, row_object.title)

        return render(request, "depart_edit.html", {"row_object": row_object})

    # 得到用户提交的标题
    title = request.POST.get("title")
    # 根据id进行修改
    models.Department.objects.filter(id=nid).update(title=title)

    return redirect("/depart/list")


def depart_multi(request):
    # 批量上传excel文件

    # 获取用户上传的文件对象
    file_object = request.FILES.get('exc')
    # print(type(file_object)) # <class 'django.core.files.uploadedfile.InMemoryUploadedFile'>

    # 把对象传递给openpyxl,读取文件的内容
    wb = load_workbook(file_object)
    # 得到该excel的第一个sheet
    sheet = wb.worksheets[0]

    # 得到第一行第二列单元格的内容
    # cell = sheet.cell(1, 2)
    # print(cell.value)

    # 循环获取从第二行开始每一行的数据
    for row in sheet.iter_rows(min_row=2):
        content = row[0].value
        # print(content)
        exists = models.Department.objects.filter(title=content).exists()
        if not exists:
            models.Department.objects.create(title=content)

    return redirect('/depart/list/')

app01/templates/error.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ msg }}</div>
    </div>
{% endblock %}

app01/templates/order_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <input id="btnAdd" type="button" value="新建订单" class="btn btn-primary">
            {#            <input type="button" value="新建订单2" class="btn btn-primary" data-toggle="modal" data-target="#myModal">#}
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                订单列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>订单号</th>
                    <th>名称</th>
                    <th>价格</th>
                    <th>状态</th>
                    <th>发起者</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr uid="{{ obj.id }}">
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.oid }}</td>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>{{ obj.admin.username }}</td>
                        <td>
                            <input uid="{{ obj.id }}" type="button" class="btn btn-primary btn-xs btn-edit" value="编辑">
                            <input uid="{{ obj.id }}" type="button" class="btn btn-danger btn-xs btn-delete" value="删除">
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

    <!-- 新建/编辑订单对话框 -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建订单</h4>
                </div>

                <div class="modal-body">
                    <form id="formAdd">
                        {# 可以不需要crsf_token，因为是通过Ajax提交 #}
                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                <span class="error-msg" style="color: red"></span>
                            </div>
                        {% endfor %}
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnSave" type="button" class="btn btn-primary">提 交</button>
                </div>
            </div>
        </div>
    </div>

    <!--删除订单对话框 -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <h4>是否确定删除？</h4>
                <p style="margin: 10px 0;">删除后，所有相关联数据将会消失！</p>
                <p style="text-align: right">
                    <button id="btnConfirmDelete" type="button" class="btn btn-danger">确 定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        var DELETE_ID;
        var EDIT_ID;

        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnEditEvent();
        })

        function bindBtnAddEvent() {
            $('#btnAdd').click(function () {
                // 清空框中原有的内容
                $('#formAdd')[0].reset();
                // 置空正在编辑的EDIT_ID
                EDIT_ID = undefined;
                // 修改对话框的标题
                $('#myModalLabel').text("新建");
                {# 点击新建按钮，显示对话框 #}
                $('#myModal').modal('show');
            })
        }

        function bindBtnSaveEvent() {
            $('#btnSave').click(function () {

                {#点击之前先清除所有的错误信息#}
                $(".error-msg").empty()

                {#alert("保存")#}
                if (EDIT_ID) {
                    // 编辑
                    doEdit();
                } else {
                    // 添加
                    doAdd();
                }
            })
        }

        function doAdd() {
            // 添加的Ajax请求
            $.ajax({
                url: '/order/add/',
                type: 'post',
                data: $('#formAdd').serialize(),
                dataType: 'JSON',
                success: function (res) {
                    {#console.log(res)#}
                    if (res.status) {
                        {# 返回了成功 #}
                        {# alert("创建成功") #}
                        {#清空表单 $("#formAdd")是一个jQuery对象 -> $("#formAdd")[0]是DOM对象，有reset方法#}
                        $("#formAdd")[0].reset();
                        {#关闭对话框#}
                        $("#myModal").modal('hide');

                        {#刷新页面#}
                        location.reload();
                    } else {
                        {# 把错误信息显示在对话框中 #}
                        $.each(res.error, function (name, errorList) {
                            $('#id_' + name).next().text(errorList[0]);
                        })
                    }
                }
            })
        }

        function doEdit() {
            // 编辑的Ajax请求
            $.ajax({
                url: '/order/edit/' + '?uid=' + EDIT_ID,
                type: 'post',
                data: $('#formAdd').serialize(),
                dataType: 'JSON',
                success: function (res) {
                    {#console.log(res)#}
                    if (res.status) {
                        {#清空表单#}
                        $("#formAdd")[0].reset();
                        {#关闭对话框#}
                        $("#myModal").modal('hide');

                        {#刷新页面#}
                        location.reload();
                    } else {
                        if (res.tips) {
                            alert(res.tips)
                        } else {
                            {# 把错误信息显示在对话框中 #}
                            $.each(res.error, function (name, errorList) {
                                $('#id_' + name).next().text(errorList[0]);
                            })
                        }
                    }
                }
            })
        }

        function bindBtnDeleteEvent() {
            $('.btn-delete').click(function () {
                {#alert('点击了删除');#}
                // 显示删除对话框
                $('#deleteModal').modal('show');

                // 获取当前行的id并赋值给全局变量
                DELETE_ID = $(this).attr('uid');
            })
        }

        function bindBtnConfirmDeleteEvent() {
            $('#btnConfirmDelete').click(function () {
                // 点击确认删除，就把全局变量中存着的id发送到后台
                $.ajax({
                    url: '/order/delete/', // ->/order/delete/?uid=***
                    type: 'GET',
                    data: {
                        uid: DELETE_ID
                    },
                    dataType: 'JSON',
                    success: function (res) {
                        if (res.status) {
                            location.reload();
                        } else {
                            // 删除失败
                            alert(res.error)
                        }
                    }
                })
            })
        }

        function bindBtnEditEvent() {
            $('.btn-edit').click(function () {
                // 清空框中原有的内容
                $('#formAdd')[0].reset();

                var uid = $(this).attr('uid');
                EDIT_ID = uid;

                // 发送Ajax去后端获取数据
                $.ajax({
                    url: '/order/detail', //order/detail/?uid=***
                    type: 'GET',
                    data: {
                        uid: uid
                    },
                    dataType: 'JSON',
                    success: function (res) {
                        {#console.log(res)#}
                        if (res.status) {
                            {#console.log(res.data)#}
                            // 填充数据
                            $.each(res.data, function (name, value) {
                                $('#id_' + name).val(value);
                            })

                            // 修改对话框的标题
                            $('#myModalLabel').text("编辑")
                            {# 显示框 #}
                            $('#myModal').modal('show');
                        } else {
                            alert(res.error)
                        }
                    }
                })
            })
        }

    </script>
{% endblock %}

app01/templates/user_list.html
{% extends "layout.html" %}

{% block content %}

    <div class="container">
        <div style="margin-bottom: 10px">
{#            <a class="btn btn-success" href="/user/add/">#}
{#                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>#}
{#                新建用户#}
{#            </a>#}

            <a class="btn btn-success" href="/user/model/form/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                ModelForm新建用户
            </a>
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用户列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>性别</th>
                    <th>年龄</th>
                    <th>工资卡余额</th>
                    <th>入职时间</th>
                    <th>所属部门</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.password }}</td>
                        {# 通过'get_字段名_display'方法可以直接在表内查找因choices被限制的字段 #}
                        <td>{{ obj.get_sex_display }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.account }}</td>
                        {# 在html模板语言中特殊的对时间进行格式化的方式 #}
                        <td>{{ obj.create_time|date:"Y-m-d" }}</td>
                        {# 通过'外键名.title'可以直接实现级联查找，是django封装的方法 #}
                        <td>{{ obj.depart.title }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <ul class="pagination">
            {{ page_string }}
        </ul>
    </div>

{% endblock %}